### PR TITLE
Upgrade Jetty to version 12

### PR DESCRIPTION
**Pull request by joris-lambrechts**
Hi,

Thanks for maintaining the fork, it's great to have a drop-in replacement that works.
We use this in multiple projects for our integration testing and we would like to keep on doing that.

As we use Spring Boot 3 we noticed a dependency conflict for Jetty.
We can mitigate it by being explicitly overriding the Jetty version that Spring Boot defines.
I got that from https://github.com/javalin/javalin/issues/2067 and it works just fine.

Just like Javalin, Spark runs on an older version of Jetty.
Javalin plans an upgrade of Jetty by the end of the year.

For Spark I upgraded it in this PR in an attempt to eventually remove the dependency conflict with Spring Boot 3.
Please feel free to provide any feedback.

Best regards,
Joris

### CODE REVIEW

**Comment by joris-lambrechts** [comment]
@nmondal if possible, could you have a look a this please?

**Comment by shivuchikkappa** [comment]
@joris-lambrechts Is it possible to update the Jetty version to 12.0.12 or later version since the earlier version has medium [CVE](url) reported 

@nmondal any timeline on when this would be merged ?

**Comment by joris-lambrechts** [comment]
@shivuchikkappa done

**Comment by nmondal** [comment]
Let me go about it as soon as possible. Sorry, I was not really looking at it. Will do.

**Comment by nmondal** [comment]
@joris-lambrechts  one test is failing -- `testCreateSecureSocketConnector`  due to missing 

```
final String keystoreFile = "./target/test-classes/keystoreFile.jks";
final String keystorePassword = "keystorePassword";
final String truststoreFile = "./target/test-classes/truststoreFile.jks";
final String trustStorePassword = "trustStorePassword";
```

Care to check please? Or I do not recall, was it failing all the time before? I do not think so.

**Comment by joris-lambrechts** [comment]
Hi @nmondal, I'll give it a look somewhere this week

**Comment by nmondal** [comment]
@joris-lambrechts  -- you probably do not need to do that, you have already done a lot. :-)

Here is the latest code -- which I think I made backward compatible by hacking through.. please let me know if it works then I would release.

https://github.com/nmondal/spark-11/commit/f54d4a47b9619ab1c981c387afc98dcb65ebc5a7

Thanks and best!

**Comment by nmondal** [comment]
Updated note -- in case you are using `pathInfo()` in the `spark.Request` it would come as `null` post migration. So we have to use `uri()`.

Related changes in my other project is as follows - added as reference.

https://github.com/nmondal/cowj/pull/129/files

**Comment by joris-lambrechts** [comment]
Hi @nmondal 

I updated my branch with the latest changes and also published the resources (https://github.com/nmondal/spark-11/pull/15).

If I run the tests again, `spark.staticfiles.StaticFilesTestExternal#testDirectoryTraversalProtectionExternal` keeps failing, don't see why atm.

**Comment by nmondal** [comment]
Let me see.

**Pull request merged**
